<?php require_once('/xampp/htdocs/criptonoticias/templates/header.phtml'); ?>

<form class="w-50 mx-auto my-5" action="/criptonoticias/secciones/actualizar/<?= $id ?>" method="POST" enctype="multipart/form-data">
    <div class="mb-3">
        <label for="tipo" class="form-label">Tipo</label>
        <input type="text" class="form-control" name="tipo" id="tipo" placeholder="Escribe un tipo de seccion, Ej: Software">
    </div>

    <button type="submit" class="btn btn-warning w-100">Actualizar seccion</button>
</form>

<?php require_once('/xampp/htdocs/criptonoticias/templates/footer.phtml'); ?>