<?php
// Pregunta si en la session esta seteado el rol en el array.
if(isset($_SESSION['rol'])){
    if($_SESSION['rol'] == 'usuario'){ // Si el rol es usuario muestra la navbar de usuario.
        include_once 'src/templates/head/userhead.phtml';
    } else if($_SESSION['rol'] == 'admin') { // Si es admin muestra el nav de admin.
        include_once 'src/templates/head/adminhead.phtml';
    }
} else {
    // Si no hay sesión definida, muestra el menú de invitado.
    include_once 'src/templates/head/defaulthead.phtml';
}
?>