
<?php require_once('/xampp/htdocs/criptonoticias/templates/header.phtml'); ?>

    <section class="noticia">
        <div class="card mb-4">
            <img src="../<?=$noticia['imagen']?>" class="card-img-top">
            <div class="card-body">
                <div class="border-bottom p-2 mb-3">
                    <h1 class="card-title"><?=$noticia['titulo']?></h1>
                    <h5 class="card-text text-muted"><?=$noticia['subtitulo']?></h5>
                </div>
                <p class="card-text"><?=$noticia['descripcion']?> </p>
                <p class="card-text">Seccion: <?=$noticia['tipo']?></p>
            </div>
        </div>
      </section>


    <?php require_once('/xampp/htdocs/criptonoticias/templates/footer.phtml'); ?>
