<?php include_once 'src/templates/header.phtml'; ?>

<div class="mb-3">

    <form method="GET" action="filtrar" class="d-flex">
        <select class="form-select form-select-lg" name="seccion">
            <option selected>Selecciona una categoria</option>
            <?php foreach ($secciones as $seccion) { ?>
                <option value="<?= $seccion['id'] ?>"><?= $seccion['tipo'] ?></option>
            <?php } ?>
        </select>
        <button type="submit" class="btn btn-success">Filtrar</button>
    </form>

</div>

<section class="noticias my-3">
    <?php foreach ($noticias as $noticia) { ?>
        <div class="card">
            <img src="<?= $noticia['imagen'] ?>" class="card-img-top" alt="...">
            <div class="card-body">
                <h3 class="card-title"><?= $noticia['titulo'] ?></h3>
                <p class="card-text"><?= $noticia['subtitulo'] ?></p>
                <p class="card-text"><?= $noticia['tipo'] ?></p>
                <a href="/criptonoticias/noticia/<?= $noticia['id'] ?>" class="btn btn-outline-primary">Leer más</a>
            </div>
        </div>
    <?php } ?>
</section>


<?php include_once 'src/templates/footer.phtml'; ?>